# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [5]:
import numpy as np


### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)


In [5]:
# matrix
print('Matrix A:\n', A)

Matrix A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
print('Dimension:', A.ndim)

Dimension: 2


In [24]:
print('Shape: ', A.shape)
#3 rows, 5 columns

Shape:  (3, 5)


In [8]:
print('Size', A.size)

Size 15


In [9]:
print('Datatype: ', A.dtype)

Datatype:  int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [14]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print('Matrix B:\n', B)
print()
print('Matrix C:\n', C)

Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [15]:
# Elementwise subtraction
subtraction = B - C
print('Elementwise subtraction:')
print (subtraction)


Elementwise subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [21]:
# Elementwise multiplication
multiplication = B * C
print('Elementwise multiplication:')
print (multiplication)

Elementwise multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [18]:
# Matrix Multiplication
matrix_multiplication = B @ C
print('Matrix Multiplication:')
print (matrix_multiplication)

Matrix Multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [23]:
# Or multiplication by using dot function method
dot_multiplication = B.dot(C)
print('Matrix Multiplication by dot:')
print (dot_multiplication)

Matrix Multiplication by dot:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [25]:
D = np.arange(1, 10).reshape(3, 3)
print("Matrix D:")
print(D)

Matrix D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# Exponated D elementwise
print("Exponated D element wise:")
D_exp = np.exp(D)
print(D_exp)

Exponated D element wise:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [30]:
# Minimum value in the whole matrix
min_value = np.min(D)
print("Minimum value in D:", min_value)

Minimum value in D: 1


In [31]:
# Minimum value in each row
min_row = np.min(D, axis=1)
print("Minimum value in each row:")
print(min_row)

Minimum value in each row:
[1 4 7]


In [32]:
# Minimum value in each column
min_col = np.min(D, axis=0)
print("Minimum value in each column:")
print(min_col)

Minimum value in each column:
[1 2 3]


In [33]:
# Index of the minimum value in the whole matrix
min_index = np.argmin(D)
print("Index of minimum value in the whole matrix:", min_index)

Index of minimum value in the whole matrix: 0


In [34]:
# Index of the minimum value in each row
min_index_row = np.argmin(D, axis=1)
print("Index of minimum value in each row:")
print(min_index_row)


Index of minimum value in each row:
[0 0 0]


In [35]:
# Sum of all elements
sum = np.sum(D)
print("Sum of all elements:", sum)

Sum of all elements: 45


In [37]:
# Mean for each column
mean_col = np.mean(D, axis=0)
print("Mean for each column:")
print(mean_col)

Mean for each column:
[4. 5. 6.]


In [38]:
# Median for each column
median_col = np.median(D, axis=0)
print("Median for each column:")
print(median_col)


Median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [21]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

As we know that A is 2-dimensional (3 × 5).
When we slice A with fewer indices than axes, NumPy slices along the first axes we specify, and the remaining axes are returned completely.
In the example, only 1 index (A[1]) is provided for a 2D array.
This selects row 1 (second row, 0-indexed). NumPy automatically returns the full row (second row) as a 1D array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [19]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [39]:
#  iterate elementwise 
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [44]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print('a: ', a)
print()

print('b: ', b)

a:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

b:  [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


As array (a) is a 1D array.
And b is reshape of a, that means it changes the shape of the array (a) without changing the data.
### (2, 3, -1) means:
First axis = size 2,    
Second axis = size 3    
Third axis = -1   
This means that in 3d array, there are two blocks of data, each block of data has three rows and using -1 in reshape lets NumPy calculate the missing dimension automatically   
So b has three axes (2, 3, 5)

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [53]:
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print('m1:\n', m1)
print()
print('m2:\n', m2)
print()
print('m1+m2:\n ', m1 + m2)

m1:
 [[1 2]
 [3 4]]

m2:
 [1 1]

m1+m2:
  [[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [4]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [63]:
A = np.arange(1, 5).reshape(2,2)
print('A:\n', A)

b = np.array([2, 2])
print('b\n', b)

print('\nA+b:\n',A+b)
print('\n A*b:\n', A*b)

A:
 [[1 2]
 [3 4]]
b
 [2 2]

A+b:
 [[3 4]
 [5 6]]

 A*b:
 [[2 4]
 [6 8]]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [4]:
import numpy as np

def add_mult_matrices(mat1, mat2, operation):
    """
    Perform matrix addition or multiplication 
    Parameters:
    mat1 : First input matrix.
    mat2 : Second input matrix.
    operation : 'add' or 'multiply'.

    Returns:
        Result of the addition or multiplication.

    TypeError:
        If inputs are not numpy arrays.
    ValueError:
        If operation is invalid or matrix shapes do not conform.
    """

    # 1. Validate input types
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise TypeError("Both inputs must be numpy arrays (np.ndarray).")

    # 2. Validate operation type
    if operation not in ('add', 'multiply'):
        raise ValueError("Operation must be either 'add' or 'multiply'.")

    # 3. Perform addition
    if operation == 'add':
        if mat1.shape != mat2.shape:
            raise ValueError(f"Matrices must have the same shape for addition. Got {mat1.shape} and {mat2.shape}.")
        return mat1 + mat2

    # 4. Perform multiplication 
    elif operation == 'multiply':
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError(f"Number of columns in the first matrix must equal number of rows in the second. Got {mat1.shape} and {mat2.shape}.")
        return mat1 @ mat2


A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("Add: ", add_mult_matrices(A, B, 'add'))
print()

# Multiplication
print("Muliply: ", add_mult_matrices(A, B, 'multiply'))
print()

# Error examples
C = np.array([1, 2])
print('Error handling!')
print("add", add_mult_matrices(A, C, 'add'))  
print(add_mult_matrices(A, B, 'divide'))             


Add:  [[ 6  8]
 [10 12]]

Muliply:  [[19 22]
 [43 50]]

Error handling!


ValueError: Matrices must have the same shape for addition. Got (2, 2) and (2,).

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

### Exercise 10.1.1

In [6]:
""" Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. """
# Solving : exercise 10.1

print("\nUppgift 10.1.1")
x = np.array([[4, 3]]) 
print('x:', x)


Uppgift 10.1.1
x: [[4 3]]


In [73]:
# (a) Dimensionen of x
print("(a) Dimensionen of x:", x.shape)

(a) Dimensionen of x: (1, 2)


In [78]:
# (b) 5 x
print("(b) 5x =", 5 * x)

(b) 5x = [[20 15]]


In [77]:
# (c) 3 x
print("(c) 3x =", 3 * x)

(c) 3x = [[12  9]]


In [76]:
# (d) 5 x + 3 x
d = add_mult_matrices(5 * x, 3 * x, "add")
print("(d) 5x + 3x =", d)

(d) 5x + 3x = [[32 24]]


In [79]:
# (e) 8 x
print("(e) 8x =", 8 * x)

(e) 8x = [[32 24]]


In [80]:
# (f) 4 x - x
print("(f) 4x - x =", 4 * x - x)

(f) 4x - x = [[12  9]]


In [81]:
# (g) x^T
xT = x.T
print("(g) x^T =", xT, "   dimension:", xT.shape)

(g) x^T = [[4]
 [3]]    dimension: (2, 1)


In [82]:
# (h) Is x + x^T defined?
try:
    add_mult_matrices(x, xT, "add")
    print("(h) JA, x + x^T är definierat.")
except:
    print("(h) NEJ, x + x^T är INTE definierat (olika dimensioner).")

(h) NEJ, x + x^T är INTE definierat (olika dimensioner).


In [84]:
# (i) ||x||
norm_x = np.linalg.norm(x)
print("(i) ||x|| =", norm_x)


(i) ||x|| = 5.0


### Exercise 10.1.2

In [7]:
# Exercise 10.1.2

v = np.array([[3],
              [7],
              [0],
              [11]])


In [88]:
# (a) Dimension
print("(a) Dimensionen of v:", v.shape)

(a) Dimensionen of v: (4, 1)


In [95]:
# (b) 2 v
print("2v = ", 2 * v)

2v =  [[ 6]
 [14]
 [ 0]
 [22]]


In [96]:
# (c) 5 v + 2 v
c = add_mult_matrices(5 * v, 2 * v, "add")
print("5v + 2v =", c)

5v + 2v = [[21]
 [49]
 [ 0]
 [77]]


In [8]:
# (d) 4 v - 2 v
print("(d) 4v - 2v =", 4 * v - 2 * v)

(d) 4v - 2v = [[ 6]
 [14]
 [ 0]
 [22]]


In [9]:
# (e) v^T
vT = v.T
print("(e) v^T =", vT, "  dimension:", vT.shape)

(e) v^T = [[ 3  7  0 11]]   dimension: (1, 4)


In [10]:
# (f) ||v||
print("(f) ||v|| =", np.linalg.norm(v))

(f) ||v|| = 13.379088160259652


###   UPPGIFT 10.1.3

In [12]:
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

# (a) ||v1||
print("(a) ||v1|| =", np.linalg.norm(v1))

(a) ||v1|| = 7.14142842854285


In [13]:
# (b) ||v1 - v2||
print("(b) ||v1 - v2|| =", np.linalg.norm(v1 - v2))

(b) ||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [27]:
# UPPGIFT 10.2.1 
A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]])

E = np.array([[1] ,  
              [2]])

I = np.array([[1, 0], 
         [0, 1]])
#print(E)
#print(E.shape)

print("\nUPPGIFT 10.2.1\n")

# (a) 2 A
print("(a) 2A =\n", 2 * A)

# (b) B - 2 A
try:
    print("(b) B - 2A =\n", B - 2 * A)
except Exception as e:
    print("(b) Inte definierat:", e)

# (c) 3 C - 2 E
try:
    print("(c) 3C - 2E =\n", 3*C - 2*E)
except Exception as e:
    print("(c) Inte definierat:", e)

# (d) 2 D -3 C
try:
    print("(d) 2D - 3C =\n", 2*D - 3*C)
except Exception as e:
    print("(d) Inte definierat:", e)

# (e) D^T + 2 D
try:
    print("(e) D^T + 2D =\n", add_mult_matrices(D.T, 2*D, "add"))
except Exception as e:
    print("(e) Inte definierat:", e)

# (f) 2 C^T - 2 D^T
try:
    print("(f) 2C^T - 2D^T =\n", 2*C.T - 2*D.T)
except Exception as e:
    print("(f) Inte definierat:", e)

# (g) A^T - B
try:
    print("(g) A^T - B =\n", add_mult_matrices(A.T, B, "add"))
except Exception as e:
    print("(g) Inte definierat:", e)

# (h) AC
try:
    print("(h) AC =\n", add_mult_matrices(A, C, "multiply"))
except Exception as e:
    print("(h) Inte definierat:", e)

# (i) CD
try:
    print("(i) CD =\n", add_mult_matrices(C, D, "multiply"))
except Exception as e:
    print("(i) Inte definierat:", e)

# (j) CB
try:
    print("(j) CB =\n", add_mult_matrices(C, B, "multiply"))
except Exception as e:
    print("(j) Inte definierat:", e)

# (k) CI
try:
    print("(k) CI =\n", add_mult_matrices(C, I, "multiply"))
except Exception as e:
    print("(k) Inte definierat:", e)

# (l) AB^T
try:
    print("(l) AB^T =\n", add_mult_matrices(A, B.T, "multiply"))
except Exception as e:
    print("(l) Inte definierat:", e)



UPPGIFT 10.2.1

(a) 2A =
 [[ 4  2 -2]
 [ 2 -2  2]]
(b) B - 2A =
 [[ 0 -4  3]
 [ 0 -2 -4]]
(c) 3C - 2E =
 [[ 1  4]
 [ 2 -1]]
(d) 2D - 3C =
 [[3 2]
 [2 3]]
(e) D^T + 2D =
 [[ 9 12]
 [12  9]]
(f) 2C^T - 2D^T =
 [[-4 -4]
 [-4 -4]]
(g) Inte definierat: Matrices must have the same shape for addition. Got (3, 2) and (2, 3).
(h) Inte definierat: Number of columns in the first matrix must equal number of rows in the second. Got (2, 3) and (2, 2).
(i) CD =
 [[11 10]
 [10 11]]
(j) CB =
 [[  8 -10  -3]
 [ 10  -8   0]]
(k) CI =
 [[1 2]
 [2 1]]
(l) AB^T =
 [[5 2]
 [7 4]]


In [72]:
# UPPGIFT 10.2.2 


print("\nUPPGIFT 10.2.2\n")

A2 = np.array([[2, 3, 4],
               [5, 4, 1]])

A2_AT = add_mult_matrices(A2, A2.T, "multiply")
print("A A^T =\n", A2_AT)



UPPGIFT 10.2.2

A A^T =
 [[29 26]
 [26 42]]


In [11]:
#UPPGIFT 10.2.3
import numpy as np

def add_mult_matrices(mat1, mat2, operation):
 
    # 1. Validate input types
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise TypeError("Both inputs must be numpy arrays (np.ndarray).")

    # 2. Validate operation type
    if operation not in ('multiply'):
        raise ValueError("Operation must be 'multiply'.")

    # 4. Perform multiplication 
    elif operation == 'multiply':
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError(f"Number of columns in the first matrix must equal number of rows in the second. Got {mat1.shape} and {mat2.shape}.")
        return mat1 @ mat2

print("\nUPPGIFT 10.2.3\n")

A = np.array([[1, 2],
               [2, 4]])

B = np.array([[2, 1],
               [1, 3]])

C = np.array([[4, 3],
               [0, 2]])

AB = add_mult_matrices(A, B, "multiply")
AC = add_mult_matrices(A, C, "multiply")

print("AB =\n", AB)
print("AC =\n", AC)

if np.array_equal(AB, AC):
    print("AB = AC (korrekt)")
else:
    print("→ Något är fel!")

print("\nMen B is !=  C:")
print("B =\n", B)
print("C =\n", C)



UPPGIFT 10.2.3

AB =
 [[ 4  7]
 [ 8 14]]
AC =
 [[ 4  7]
 [ 8 14]]
AB = AC (korrekt)

Men B is !=  C:
B =
 [[2 1]
 [1 3]]
C =
 [[4 3]
 [0 2]]


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [29]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


Slicing v1[-2:] returns a view, not a copy. And view shares the same data as the original array.   
A copy is a new array with its own memory.   
   
We can check if two arrays share the same memory or not by using np.shares_memory

In [30]:

np.shares_memory(v1, v2) #if true, they share same memory: its a view


True

In [31]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [33]:
v2[-1] = 123
print("v1: ", v1) 
print("v2: ", v2) 

v1:  [  0   1   2 123]
v2:  [  2 123]


The last element of v1 is also changed because v2 is a view.   
As v1 and v2 points to the same memory, so modifying one affects the other (view). 

In [14]:
""" Using .copy() creates a separate array that does not affect v1. """
v2_copy = v1[-2:].copy()
v2_copy[-1] = 999
print(v2_copy)  
print(v1)     

[  2 999]
[  0   1   2 123]
